name: ci-engine

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ci:
    name: Lint and test engine
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - 3.6

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint engine
        run: black engine/ --check

      - name: Test engine
        run: coverage run -m unittest discover

      - name: Print test report
        run: coverage report -m
